---

- hosts: consul 
  pre_tasks:
  - name: install unzip
    yum:
      name: unzip
      state: present
    become: true

  tasks:
  - name: add group consul 
    group:
      name: consul
      state: present

  - name: add user consul 
    user:
      name: consul 
      group: consul 
      shell: /sbin/nologin
      create_home: no 

  - name: create directory
    file:
      path: "{{item.path}}"
      state: directory
      owner: consul
      group: consul
    with_items:
      - {path: "/etc/consul.d"}
      - {path: "/data/consul"}

  - name: download consul zip file
    unarchive: 
      src: https://releases.hashicorp.com/consul/1.6.1/consul_1.6.1_linux_amd64.zip
      remote_src: yes
      dest: /usr/local/bin 
      mode: o+x

  - name: create config file
    template:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
      group: "{{item.group}}" 
      owner: "{{item.owner}}" 
    with_items:
      - {src: temp_consul.j2, dest: /etc/consul.d/consul.json, group: consul ,owner: consul}
      - {src: temp_consul_systemctl.j2, dest: /lib/systemd/system/consul.service, group: root ,owner: root}

  - name: enable bind 53
    command: setcap CAP_NET_BIND_SERVICE=+eip /usr/local/bin/consul
    become: true

  - name: systemd consul
    systemd:
      name: "consul"
      daemon_reload: yes
      state: started
      enabled: yes
    


